# Generated by Django 6.0.5 on 2026-05-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='eligible_branches',
            field=models.TextField(default='All', help_text='e.g., Computer Science, IT or All'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='min_cgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
