# Generated by Django 6.0.5 on 2026-06-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='application_deadline',
            field=models.DateField(blank=True, help_text='Deadline to apply for this drive', null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='drive_date',
            field=models.DateField(blank=True, help_text='Date of recruitment drive / tests / interviews', null=True),
        ),
    ]
